import type { FeedPost, ProfessionalProfile } from "./types";

export const previewProfiles: ProfessionalProfile[] = [
  {
    walletAddress: "NQ84…0QJ2",
    displayName: "Tomi A.",
    bio: "I turn wallet and payment complexity into calm, accessible product flows.",
    profileRole: "worker",
    professionalTitle: "Frontend engineer",
    skills: ["React", "Nimiq", "Design systems"],
    availability: "open",
    workPreference: "remote",
    location: "Lagos · Remote",
    onboardingCompletedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    followers: 184,
    following: 72,
    isFollowing: false,
    reputation: {
      score: 94,
      reviewCount: 11,
      confidence: 100,
      dimensions: {
        quality: 4.8,
        delivery: 4.7,
        communication: 4.6,
        reliability: 4.8,
      },
      credentialTxHash: null,
    },
    preview: true,
    completedJobs: 12,
    earned: "4,280 USDT",
    workSamples: [
      {
        title: "Wallet onboarding system",
        outcome: "Reduced a five-step wallet flow to three clear decisions.",
        skills: ["React", "Nimiq"],
      },
      {
        title: "Escrow progress workspace",
        outcome: "Designed proof, review, and dispute states for mobile.",
        skills: ["UX", "Web3"],
      },
    ],
  },
  {
    walletAddress: "NQ12…4K8H",
    displayName: "Amara K.",
    bio: "Product founder commissioning compact, useful work from independent teams.",
    profileRole: "client",
    professionalTitle: "Product founder",
    skills: ["Product strategy", "Fintech", "Motion"],
    availability: "open",
    workPreference: "flexible",
    location: "Berlin · Remote",
    onboardingCompletedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    followers: 96,
    following: 118,
    isFollowing: false,
    reputation: {
      score: 91,
      reviewCount: 8,
      confidence: 100,
      dimensions: {
        quality: 4.5,
        delivery: 4.7,
        communication: 4.6,
        reliability: 4.4,
      },
      credentialTxHash: null,
    },
    preview: true,
    completedJobs: 9,
    earned: "8 jobs funded",
    workSamples: [
      {
        title: "Wallet product story",
        outcome: "Commissioning a 40-second onboarding narrative.",
        skills: ["Motion", "Product video"],
      },
    ],
  },
  {
    walletAddress: "NQ44…9L0M",
    displayName: "Nia Studio",
    bio: "Identity systems for early Web3 products, from mark to first product screens.",
    profileRole: "worker",
    professionalTitle: "Brand and product studio",
    skills: ["Brand systems", "Product UI", "Identity"],
    availability: "busy",
    workPreference: "remote",
    location: "Accra · Remote",
    onboardingCompletedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    followers: 241,
    following: 51,
    isFollowing: true,
    reputation: {
      score: 97,
      reviewCount: 16,
      confidence: 100,
      dimensions: {
        quality: 4.9,
        delivery: 4.8,
        communication: 4.9,
        reliability: 4.8,
      },
      credentialTxHash: null,
    },
    preview: true,
    completedJobs: 18,
    earned: "7,950 USDT",
    workSamples: [
      {
        title: "Proof-path identity",
        outcome: "Created a compact identity that holds at favicon scale.",
        skills: ["Identity", "UI systems"],
      },
    ],
  },
  {
    walletAddress: "NQ61…7P3D",
    displayName: "Kemi O.",
    bio: "Smart contracts, payment rails, and adversarial state testing.",
    profileRole: "worker",
    professionalTitle: "Smart contract engineer",
    skills: ["Solidity", "Escrow", "Security"],
    availability: "open",
    workPreference: "remote",
    location: "Nairobi · Remote",
    onboardingCompletedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    followers: 132,
    following: 89,
    isFollowing: false,
    reputation: {
      score: 95,
      reviewCount: 13,
      confidence: 100,
      dimensions: {
        quality: 4.8,
        delivery: 4.8,
        communication: 4.5,
        reliability: 4.9,
      },
      credentialTxHash: null,
    },
    preview: true,
    completedJobs: 14,
    earned: "11,200 USDT",
    workSamples: [
      {
        title: "Milestone escrow",
        outcome:
          "Shipped settlement and timeout protections with full state tests.",
        skills: ["Solidity", "Security"],
      },
    ],
  },
];

export const previewPosts: FeedPost[] = [
  {
    id: "preview-request",
    authorWallet: "NQ12…4K8H",
    authorName: "Amara K.",
    authorRole: "Product founder",
    kind: "request",
    body: "Looking for a motion designer to turn our onboarding flow into a 40-second product story. Clear handoff, three scenes, mobile-first.",
    jobId: "job_preview_motion",
    requiredLuna: "10000",
    paymentTxHash: "preview",
    publishedAt: new Date(Date.now() - 11 * 60_000).toISOString(),
    createdAt: new Date(Date.now() - 11 * 60_000).toISOString(),
    budget: "350 USDT",
    skills: ["Motion", "Product video"],
    engagement: {
      replies: 2,
      reposts: 2,
      appreciations: 12,
      bookmarks: 4,
      viewer: { reposted: false, appreciated: false, bookmarked: false },
    },
    preview: true,
  },
  {
    id: "preview-proof",
    authorWallet: "NQ84…0QJ2",
    authorName: "Tomi A.",
    authorRole: "Frontend engineer",
    kind: "proof",
    body: "Milestone 2 shipped: wallet connection, signed login, and the full empty/error state pass. Lighthouse accessibility is next.",
    jobId: "job_preview_build",
    requiredLuna: "1000",
    paymentTxHash: "preview",
    publishedAt: new Date(Date.now() - 47 * 60_000).toISOString(),
    createdAt: new Date(Date.now() - 47 * 60_000).toISOString(),
    proofLabel: "Milestone 2 of 3",
    skills: ["React", "Nimiq"],
    engagement: {
      replies: 2,
      reposts: 5,
      appreciations: 12,
      bookmarks: 7,
      viewer: { reposted: false, appreciated: false, bookmarked: false },
    },
    preview: true,
  },
  {
    id: "preview-service",
    authorWallet: "NQ44…9L0M",
    authorName: "Nia Studio",
    authorRole: "Brand systems",
    kind: "service",
    body: "I build identity systems for small Web3 products: naming, mark, color, type, and the first five product screens—without the usual crypto visual noise.",
    jobId: null,
    requiredLuna: "10000",
    paymentTxHash: "preview",
    publishedAt: new Date(Date.now() - 3 * 3_600_000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 3_600_000).toISOString(),
    budget: "From 500 USDT",
    skills: ["Identity", "UI systems"],
    engagement: {
      replies: 2,
      reposts: 2,
      appreciations: 24,
      bookmarks: 9,
      viewer: { reposted: false, appreciated: false, bookmarked: false },
    },
    preview: true,
  },
];
