import type { FeedPost } from "./types";

export const previewPosts: FeedPost[] = [
  {
    id: "preview-request",
    authorWallet: "NQ12…4K8H",
    authorName: "Amara K.",
    authorRole: "Product founder",
    kind: "request",
    body: "Looking for a motion designer to turn our onboarding flow into a 40-second product story. Clear handoff, three scenes, mobile-first.",
    jobId: "job_preview_motion",
    requiredLuna: "10000",
    paymentTxHash: "preview",
    publishedAt: new Date(Date.now() - 11 * 60_000).toISOString(),
    createdAt: new Date(Date.now() - 11 * 60_000).toISOString(),
    budget: "350 USDT",
    skills: ["Motion", "Product video"],
    preview: true,
  },
  {
    id: "preview-proof",
    authorWallet: "NQ84…0QJ2",
    authorName: "Tomi A.",
    authorRole: "Frontend engineer",
    kind: "proof",
    body: "Milestone 2 shipped: wallet connection, signed login, and the full empty/error state pass. Lighthouse accessibility is next.",
    jobId: "job_preview_build",
    requiredLuna: "1000",
    paymentTxHash: "preview",
    publishedAt: new Date(Date.now() - 47 * 60_000).toISOString(),
    createdAt: new Date(Date.now() - 47 * 60_000).toISOString(),
    proofLabel: "Milestone 2 of 3",
    skills: ["React", "Nimiq"],
    preview: true,
  },
  {
    id: "preview-service",
    authorWallet: "NQ44…9L0M",
    authorName: "Nia Studio",
    authorRole: "Brand systems",
    kind: "service",
    body: "I build identity systems for small Web3 products: naming, mark, color, type, and the first five product screens—without the usual crypto visual noise.",
    jobId: null,
    requiredLuna: "10000",
    paymentTxHash: "preview",
    publishedAt: new Date(Date.now() - 3 * 3_600_000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 3_600_000).toISOString(),
    budget: "From 500 USDT",
    skills: ["Identity", "UI systems"],
    preview: true,
  },
];
