import { useEffect, useId, useRef, useState, type FormEvent } from "react";
import { ArrowLeft, ArrowRight, BriefcaseBusiness, Check, Sparkles, UserRound, Users, X } from "lucide-react";
import type { ProfileInput, ProfileRole } from "../types";

const roles:Array<{value:ProfileRole;title:string;copy:string;icon:typeof UserRound}>=[
  {value:"worker",title:"Find work",copy:"Show what you do and discover relevant requests.",icon:UserRound},
  {value:"client",title:"Hire people",copy:"Find proven professionals and publish clear work.",icon:BriefcaseBusiness},
  {value:"both",title:"Do both",copy:"Switch naturally between hiring and delivering.",icon:Users},
];

const initial:ProfileInput={displayName:"",bio:"",profileRole:"worker",professionalTitle:"",skills:[],availability:"open",workPreference:"remote",location:""};

export function OnboardingDialog({open,saving,onClose,onSubmit}:{open:boolean;saving:boolean;onClose:()=>void;onSubmit:(input:ProfileInput)=>Promise<void>}) {
  const titleId=useId(); const dialogRef=useRef<HTMLElement>(null); const [step,setStep]=useState(1); const [input,setInput]=useState<ProfileInput>(initial); const [skillText,setSkillText]=useState("");
  useEffect(()=>{if(!open)return;const key=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!saving)onClose();if(event.key!=="Tab")return;const nodes=dialogRef.current?.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),textarea:not([disabled]),select:not([disabled]),[tabindex]:not([tabindex="-1"])');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}};document.addEventListener("keydown",key);document.body.classList.add("dialog-open");return()=>{document.removeEventListener("keydown",key);document.body.classList.remove("dialog-open");};},[open,onClose,saving]);
  if(!open)return null;
  const canContinue=step===1?true:step===2?input.displayName.trim().length>=2&&input.professionalTitle.trim().length>=2:skillText.split(",").some((skill)=>skill.trim());
  const submit=async(event:FormEvent)=>{event.preventDefault();if(step<3){setStep(step+1);return;}await onSubmit({...input,skills:[...new Set(skillText.split(",").map((skill)=>skill.trim()).filter(Boolean))].slice(0,12)});};
  return <div className="dialog-backdrop onboarding-backdrop"><section ref={dialogRef} className="onboarding-dialog" role="dialog" aria-modal="true" aria-labelledby={titleId}>
    <header className="onboarding-dialog__header"><BrandPath/><div className="onboarding-progress"><span>Profile setup</span><strong>{step} of 3</strong></div><button className="icon-button" type="button" onClick={onClose} disabled={saving} aria-label="Close profile setup"><X/></button></header>
    <form onSubmit={submit}>
      {step===1&&<div className="onboarding-step"><span className="eyebrow">Shape your NimSocial</span><h2 id={titleId}>What brings you here?</h2><p>This sets your starting feed. You can change it later.</p><fieldset className="role-options"><legend className="sr-only">Choose your main goal</legend>{roles.map((role)=>{const Icon=role.icon;return <label key={role.value} className={input.profileRole===role.value?"is-selected":""}><input type="radio" name="profileRole" value={role.value} checked={input.profileRole===role.value} onChange={()=>setInput({...input,profileRole:role.value})}/><Icon/><span><strong>{role.title}</strong><small>{role.copy}</small></span>{input.profileRole===role.value&&<Check/>}</label>;})}</fieldset></div>}
      {step===2&&<div className="onboarding-step"><span className="eyebrow">Your public identity</span><h2 id={titleId}>Make the first impression useful.</h2><p>Use language a collaborator would actually search for.</p><div className="onboarding-grid"><label className="field"><span>Display name</span><input autoFocus value={input.displayName} onChange={(event)=>setInput({...input,displayName:event.target.value})} minLength={2} maxLength={60} required placeholder="e.g. Tomi Ade" autoComplete="name"/></label><label className="field"><span>Professional title</span><input value={input.professionalTitle} onChange={(event)=>setInput({...input,professionalTitle:event.target.value})} minLength={2} maxLength={80} required placeholder="e.g. Frontend engineer"/></label><label className="field field--wide"><span>Short introduction</span><textarea value={input.bio} onChange={(event)=>setInput({...input,bio:event.target.value})} maxLength={280} placeholder="The work you do, the outcomes you care about, and how you collaborate."/><small>{input.bio.length}/280</small></label></div></div>}
      {step===3&&<div className="onboarding-step"><span className="eyebrow">Tune discovery</span><h2 id={titleId}>What should find you?</h2><p>These explicit preferences seed recommendations before interaction history exists.</p><div className="onboarding-grid"><label className="field field--wide"><span>{input.profileRole==="client"?"Skills you usually hire":"Your strongest skills"}</span><input autoFocus value={skillText} onChange={(event)=>setSkillText(event.target.value)} required placeholder="React, Nimiq, product design"/><small>Separate up to 12 with commas</small></label><label className="field"><span>Availability</span><select value={input.availability} onChange={(event)=>setInput({...input,availability:event.target.value as ProfileInput["availability"]})}><option value="open">Open to work</option><option value="busy">Limited availability</option><option value="not_open">Not open right now</option></select></label><label className="field"><span>Work preference</span><select value={input.workPreference} onChange={(event)=>setInput({...input,workPreference:event.target.value as ProfileInput["workPreference"]})}><option value="remote">Remote</option><option value="hybrid">Hybrid</option><option value="onsite">On-site</option><option value="flexible">Flexible</option></select></label><label className="field field--wide"><span>Location <em>optional</em></span><input value={input.location} onChange={(event)=>setInput({...input,location:event.target.value})} maxLength={80} placeholder="City, country or Remote" autoComplete="address-level2"/></label></div><div className="algorithm-note"><Sparkles/><div><strong>How matching starts</strong><span>Role + skills + availability + follows. Completed work and useful interactions improve it over time.</span></div></div></div>}
      <footer className="onboarding-dialog__footer"><button className="button button--quiet" type="button" onClick={()=>step===1?onClose():setStep(step-1)} disabled={saving}>{step===1?"Not now":<><ArrowLeft/>Back</>}</button><button className="button button--primary" type="submit" disabled={saving||!canContinue}>{saving?"Saving…":step===3?<>Finish profile<Check/></>:<>Continue<ArrowRight/></>}</button></footer>
    </form>
  </section></div>;
}

function BrandPath(){return <div className="onboarding-brand" aria-hidden="true"><span/><span/><span/></div>;}
